services:
  - type: web
    name: gametune-kit-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SWAGGER_ENABLED
        value: true
      - key: PUSH_MOCK_MODE
        value: false
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_TYPE
        value: postgres
      - key: DB_SSL
        value: true
      - key: VAPID_PUBLIC_KEY
        value: BMP47yhOvCtTsM2PDhjzS24qzmqQnl10vqy7nIkUAPQ3QvmWutaMnyUflJuu7qXynjnWk_YdklzX1rN7loyBUvw
      - key: VAPID_PRIVATE_KEY
        value: DO2MK4W9HRzCJpUraN8KXXcnxz2NZvd2jDEHVYfwLbY
      - key: VAPID_SUBJECT
        value: mailto:admin@gametunekit.com
      - key: DATABASE_URL
        sync: false # Set in Render Dashboard with your Supabase Connection URI
